"""Which places are behind a locked door, read from the game's doors and pathgrids.

A chest's own lock is on the record, but the door in front of it is not. Briricca's
private bank in Old Ebonheart opens straight onto the street, yet its back rooms sit
behind jail doors locked at 100; the Mages Guild basement there is one flight down,
and its storeroom is behind a door locked at 60. Neither door leads to another cell,
so no cell graph sees them.

The rooms are in the pathgrids: the walking graph each interior carries for its NPCs,
which runs through doorways. A link that passes through a locked door costs that
door's lock level to cross; teleport doors join the cells up; every exterior is open.
A minimax search from the outside gives, for every pathgrid point, the lowest lock a
character must open to stand there. An item takes the value of its nearest point.

A cell no door leads into at all (Mournhold, reached by a Temple teleport) has no
answer and is reported as unknown, never as locked.
"""
from __future__ import annotations

import heapq
import json
import math
import struct

GRID = 8192           # ESM::Land::REAL_SIZE: the width of one exterior cell
DOOR_REACH = 112      # a link passing this close to a locked door goes through it
DOOR_BELOW = 64       # how far a door's origin can sit below the link it blocks
DOOR_ABOVE = 256      # and above: its height, give or take
# A locked storeroom is often a room the walking graph never enters: the Mages Guild
# basement in Old Ebonheart has no point past its door locked at 60. An item that far
# from every point and this close to a locked door, on its floor, is taken to be inside.
ROOM_GAP = 250
ROOM_REACH = 400
ROOM_FLOOR = 200
OUTSIDE = ('exterior', None)


def subrecords(payload):
    i = 0
    while i + 8 <= len(payload):
        tag = payload[i:i+4].decode('latin1')
        size = struct.unpack_from('<I', payload, i+4)[0]
        yield tag, payload[i+8:i+8+size]
        i += 8 + size


def parse_pathgrid(payload):
    """(name, (x, y), points, links) from a PGRD record; see components/esm3/loadpgrd.cpp.

    PGRP holds 16-byte points (x, y, z, autogenerated, connection count, padding);
    PGRC lists each point's neighbours in point order, as many as its count says.
    """
    name, grid, points, counts, targets = None, (0, 0), [], [], []
    for tag, body in subrecords(payload):
        if tag == 'NAME':
            name = body.split(b'\x00', 1)[0].decode('cp1252', 'replace')
        elif tag == 'DATA' and len(body) >= 8:
            grid = struct.unpack_from('<ii', body)
        elif tag == 'PGRP':
            for offset in range(0, len(body) - 15, 16):
                x, y, z, _auto, count, _pad = struct.unpack_from('<iiiBBh', body, offset)
                points.append((x, y, z))
                counts.append(count)
        elif tag == 'PGRC':
            targets = [value for (value,) in struct.iter_unpack('<i', body[:len(body) - len(body) % 4])]
    links, cursor = set(), 0
    for index, count in enumerate(counts):
        for target in targets[cursor:cursor+count]:
            if 0 <= target < len(points) and target != index:
                links.add((min(index, target), max(index, target)))
        cursor += count
    return name, grid, points, links


def interior_names(world, profile):
    """Interior cell names, folded, to their keys. OpenMW decides a pathgrid is an
    interior's when its grid is (0, 0) and an interior of that name exists."""
    return {name.casefold(): key for key, name in world.execute(
        'SELECT cell_key, name FROM cells WHERE profile_id = ? AND interior = 1 AND name IS NOT NULL',
        (profile,))}


def load_pathgrids(game, profile, interiors):
    """The winning pathgrid of every interior in the profile, by cell key."""
    order = dict(game.execute('SELECT plugin_id, load_order FROM profile_plugins WHERE profile_id = ?',
                              (profile,)))
    grids = {}
    for plugin, payload in game.execute("SELECT plugin_id, payload FROM record_versions WHERE record_type = 'PGRD'"):
        if plugin not in order:
            continue
        name, grid, points, links = parse_pathgrid(payload)
        key = interiors.get((name or '').casefold()) if grid == (0, 0) else None
        if key is None:
            continue
        if key not in grids or order[plugin] >= grids[key][0]:
            grids[key] = (order[plugin], points, links)
    return {key: (points, links) for key, (_, points, links) in grids.items()}


def load_doors(world, profile, interiors):
    """Every door in the profile: where it stands, its lock, and where it leads if anywhere."""
    doors = []
    for cell, x, y, z, details in world.execute(
            'SELECT p.cell_key, p.x, p.y, p.z, p.details FROM placements p '
            'JOIN profile_placements pp ON pp.reference_key = p.reference_key AND pp.version_id = p.version_id '
            'JOIN profile_objects po ON po.profile_id = pp.profile_id AND po.object_key = p.object_key '
            "JOIN objects o ON o.version_id = po.version_id WHERE pp.profile_id = ? AND o.record_type = 'DOOR'",
            (profile,)):
        extra = json.loads(details) if details else {}
        target = extra.get('doorDestination') or None
        leads = arrival = None
        if target:
            arrival = tuple(target.get('position') or (0, 0, 0))
            named = interiors.get(str(target.get('cellName') or '').casefold())
            leads = named or f'exterior:{math.floor(arrival[0]/GRID)},{math.floor(arrival[1]/GRID)}'
        doors.append({'cell': cell, 'at': (x or 0, y or 0, z or 0), 'lock': max(0, extra.get('lockLevelRaw') or 0),
                      'leads': leads, 'arrival': arrival})
    return doors


def segment_distance(point, a, b):
    """Horizontal distance from a point to the segment a-b."""
    ax, ay, bx, by, px, py = a[0], a[1], b[0], b[1], point[0], point[1]
    dx, dy = bx - ax, by - ay
    length = dx*dx + dy*dy
    t = 0 if not length else max(0.0, min(1.0, ((px-ax)*dx + (py-ay)*dy) / length))
    return math.hypot(px - (ax + t*dx), py - (ay + t*dy))


def link_locks(points, links, doors):
    """Each link's cost to cross: the highest lock among the locked doors it passes through."""
    locked = [d for d in doors if d['lock'] and d['leads'] is None]
    costs = {}
    for i, j in links:
        a, b = points[i], points[j]
        cost = 0
        for door in locked:
            x, y, z = door['at']
            if (min(a[2], b[2]) - DOOR_BELOW <= z <= max(a[2], b[2]) + DOOR_ABOVE
                    and segment_distance(door['at'], a, b) <= DOOR_REACH):
                cost = max(cost, door['lock'])
        costs[i, j] = cost
    return costs


def nearest(points, spot):
    """Index of the pathgrid point nearest a spot, or None for an empty grid."""
    best, index = None, None
    for i, (x, y, z) in enumerate(points):
        d = (x-spot[0])**2 + (y-spot[1])**2 + ((z-spot[2])*2)**2  # floors differ more than rooms
        if best is None or d < best:
            best, index = d, i
    return index


class DoorAccess:
    """The lowest lock a character must open to reach any spot in a profile."""

    def __init__(self, pathgrids, doors):
        self.pathgrids = pathgrids
        by_cell = {}
        for door in doors:
            by_cell.setdefault(door['cell'], []).append(door)
        self.inner = {cell: [d for d in found if d['lock'] and d['leads'] is None]
                      for cell, found in by_cell.items()}
        # The graph: the outside, each interior pathgrid point, and each interior with
        # no pathgrid as a single room.
        edges = {}

        def node(cell, spot):
            if cell is None or cell.startswith('exterior:'):
                return OUTSIDE
            grid = pathgrids.get(cell)
            if not grid or not grid[0]:
                return (cell, None)
            return (cell, nearest(grid[0], spot))

        for cell, (points, links) in pathgrids.items():
            for (i, j), cost in link_locks(points, links, by_cell.get(cell, [])).items():
                edges.setdefault((cell, i), []).append(((cell, j), cost))
                edges.setdefault((cell, j), []).append(((cell, i), cost))
        for door in doors:
            if door['leads'] is None:
                continue
            start = node(door['cell'], door['at'])
            edges.setdefault(start, []).append((node(door['leads'], door['arrival']), door['lock']))
        best = {OUTSIDE: 0}
        queue = [(0, 0, OUTSIDE)]
        counter = 0
        while queue:
            cost, _, here = heapq.heappop(queue)
            if cost > best.get(here, math.inf):
                continue
            for there, lock in edges.get(here, ()):
                reach = max(cost, lock)
                if reach < best.get(there, math.inf):
                    best[there] = reach
                    counter += 1
                    heapq.heappush(queue, (reach, counter, there))
        self.best = best

    def lock_to_reach(self, cell, spot):
        """0 when open, the lock level when a locked door is in the way, None when no
        door leads there at all (a teleport-only place), so nothing is claimed."""
        if cell.startswith('exterior:'):
            return 0
        grid = self.pathgrids.get(cell)
        if not (grid and grid[0] and spot is not None):
            return self.best.get((cell, None))
        index = nearest(grid[0], spot)
        point = grid[0][index]
        reach = self.best.get((cell, index))
        if reach is None:
            return None
        if math.hypot(point[0]-spot[0], point[1]-spot[1]) > ROOM_GAP:
            for door in self.inner.get(cell, ()):
                x, y, z = door['at']
                if abs(spot[2]-z) <= ROOM_FLOOR and math.hypot(x-spot[0], y-spot[1]) <= ROOM_REACH:
                    reach = max(reach, door['lock'])
        return reach


def door_access(world, game, profile):
    interiors = interior_names(world, profile)
    return DoorAccess(load_pathgrids(game, profile, interiors), load_doors(world, profile, interiors))
