PRAGMA foreign_keys=ON;
CREATE TABLE metadata(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE profiles(id TEXT PRIMARY KEY,world TEXT NOT NULL,version TEXT NOT NULL,arce INTEGER NOT NULL);
CREATE TABLE objects(version_id INTEGER PRIMARY KEY,record_type TEXT NOT NULL,object_key TEXT NOT NULL,editor_id TEXT NOT NULL,name TEXT NOT NULL,plugin TEXT NOT NULL,script_key TEXT,model TEXT);
CREATE TABLE profile_objects(profile_id TEXT NOT NULL REFERENCES profiles(id),record_type TEXT NOT NULL,object_key TEXT NOT NULL,version_id INTEGER NOT NULL REFERENCES objects(version_id),origin_plugin TEXT NOT NULL,PRIMARY KEY(profile_id,record_type,object_key));
CREATE INDEX object_lookup ON profile_objects(profile_id,object_key);
CREATE TABLE actors(version_id INTEGER PRIMARY KEY REFERENCES objects(version_id),kind TEXT NOT NULL,level INTEGER NOT NULL,respawns INTEGER NOT NULL,essential INTEGER NOT NULL,autocalculated INTEGER NOT NULL,details TEXT NOT NULL);
CREATE TABLE containers(version_id INTEGER PRIMARY KEY REFERENCES objects(version_id),capacity REAL NOT NULL,organic INTEGER NOT NULL,respawns INTEGER NOT NULL,flags_raw INTEGER NOT NULL);
CREATE TABLE inventories(holder_version_id INTEGER NOT NULL REFERENCES objects(version_id),entry_index INTEGER NOT NULL,object_key TEXT NOT NULL,count_raw INTEGER NOT NULL,quantity INTEGER NOT NULL,restocking INTEGER NOT NULL,PRIMARY KEY(holder_version_id,entry_index));
CREATE INDEX inventory_item ON inventories(object_key,holder_version_id);
CREATE TABLE leveled_lists(version_id INTEGER PRIMARY KEY REFERENCES objects(version_id),kind TEXT NOT NULL,chance_none INTEGER NOT NULL,flags_raw INTEGER NOT NULL);
CREATE TABLE leveled_entries(list_version_id INTEGER NOT NULL REFERENCES leveled_lists(version_id),entry_index INTEGER NOT NULL,object_key TEXT NOT NULL,minimum_level INTEGER NOT NULL,PRIMARY KEY(list_version_id,entry_index));
CREATE INDEX leveled_item ON leveled_entries(object_key,list_version_id);
CREATE TABLE actor_spells(actor_version_id INTEGER NOT NULL REFERENCES actors(version_id),entry_index INTEGER NOT NULL,spell_key TEXT NOT NULL,PRIMARY KEY(actor_version_id,entry_index));
CREATE TABLE cells(profile_id TEXT NOT NULL REFERENCES profiles(id),cell_key TEXT NOT NULL,name TEXT,interior INTEGER NOT NULL,grid_x INTEGER,grid_y INTEGER,region_key TEXT,deleted INTEGER NOT NULL,synthetic INTEGER NOT NULL,details TEXT NOT NULL,PRIMARY KEY(profile_id,cell_key));
CREATE TABLE placements(version_id INTEGER PRIMARY KEY,reference_key TEXT NOT NULL,object_key TEXT,source_cell_key TEXT NOT NULL,cell_key TEXT NOT NULL,plugin TEXT NOT NULL,record_id INTEGER NOT NULL,payload_offset INTEGER NOT NULL,payload_length INTEGER NOT NULL,moved INTEGER NOT NULL,x REAL,y REAL,z REAL,count_raw INTEGER,owner_key TEXT,faction_key TEXT,details TEXT);
CREATE INDEX placement_record ON placements(record_id,version_id);
CREATE INDEX placement_item ON placements(object_key,version_id);
CREATE INDEX placement_cell ON placements(cell_key,version_id);
CREATE TABLE profile_placements(profile_id TEXT NOT NULL REFERENCES profiles(id),reference_key TEXT NOT NULL,version_id INTEGER NOT NULL REFERENCES placements(version_id),origin_plugin TEXT NOT NULL,PRIMARY KEY(profile_id,reference_key));
CREATE INDEX placement_profile_version ON profile_placements(version_id,profile_id);
CREATE TABLE warnings(profile_id TEXT,code TEXT NOT NULL,object_key TEXT,count INTEGER NOT NULL,detail TEXT);
